/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Economystique;

public class App {
    public static void main(String[] args) {
        LoginAndSignup.main(args);
        // SwingUtilities.invokeLater(App::new);
    }
}
