/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Economystique;

public class App {
    public static void main(String[] args) {
        LoginAndSignup.main(args);
    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
