/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Economystique;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;

public class App {
    private JFrame frame;
    private JTextArea textArea;
    private JFileChooser fileChooser;

    public App() {
        // Initialize components
        frame = new JFrame("Economystique");
        textArea = new JTextArea();
        fileChooser = new JFileChooser();

        // Setup the frame
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);
        frame.setLayout(new BorderLayout());

        // Add components
        frame.add(new JScrollPane(textArea), BorderLayout.CENTER);
        frame.setJMenuBar(createMenuBar());

        // Show frame
        frame.setVisible(true);
    }

    private JMenuBar createMenuBar() {
        // Create menu bar
        JMenuBar menuBar = new JMenuBar();

        // Create File menu
        JMenu fileMenu = new JMenu("File");
        JMenu navInv = new JMenu("Inventory");
        JMenu navSales = new JMenu("Sales");
        JMenu navCal = new JMenu("Calendar");
        JMenu navAcc = new JMenu("Account");

        // Create menu items
        JMenuItem openItem = new JMenuItem("Open");
        JMenuItem saveItem = new JMenuItem("Save");
        JMenuItem exitItem = new JMenuItem("Exit");

        // Add action listeners
        openItem.addActionListener(e -> openFile());
        saveItem.addActionListener(e -> saveFile());
        exitItem.addActionListener(e -> System.exit(0));

        // Add items to File menu
        fileMenu.add(openItem);
        fileMenu.add(saveItem);
        fileMenu.addSeparator();
        fileMenu.add(exitItem);

        // Add items to menu bar
        menuBar.add(fileMenu);
        menuBar.add(navInv);
        menuBar.add(navSales);
        menuBar.add(navCal);
        menuBar.add(navAcc);
        return menuBar;
    }

    private void openFile() {
        int result = fileChooser.showOpenDialog(frame);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                textArea.read(reader, null);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(frame, "Error opening file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void saveFile() {
        int result = fileChooser.showSaveDialog(frame);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
                textArea.write(writer);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(frame, "Error saving file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(App::new);
    }
}
